.DEFAULT_GOAL: all

.PHONY: all
all: up

.PHONY: push
push:
	(cd order-gateway && make)
	(cd order-rpc-service && make)
	(cd payment-rpc-service && make)
	(cd shipping-rpc-service && make)

.PHONY: up
up:
	docker compose -f docker-compose.yaml up --build

.PHONY: commit
commit: 
	git add .
	git commit -am "more fixes"
	git push

nginx-generate-cert:
	@rm -f certs/nginx.crt
	@rm -f certs/nginx.key
	openssl req -x509 -newkey rsa:4096 -keyout certs/nginx.key -out certs/nginx.crt -days 365 \
	-nodes -subj "/CN=www.sklrsn.in" -addext "subjectAltName=DNS:sklrsn.in,DNS:www.sklrsn.in"
nginx-tls-secret-dev: nginx-generate-cert
	kubectl create namespace dev || exit 0
	kubectl create secret tls nginx-tls-secret --cert=certs/nginx.crt --key=certs/nginx.key -n dev

nginx-tls-secret-prod: nginx-generate-cert
	kubectl create namespace prod || exit 0
	kubectl create secret tls nginx-tls-secret --cert=certs/nginx.crt --key=certs/nginx.key -n prod