.DEFAULT_GOAL: all

.PHONY: all
all: compile

.PHONY: push
push:
	(cd order-gateway && make)
	(cd order-rpc-service && make)
	(cd payment-rpc-service && make)
	(cd shipping-rpc-service && make)

.PHONY: up
up:
	docker compose -f docker-compose.yaml up --build

.PHONY: commit
commit: 
	git add .
	git commit -am "more fixes"