apiVersion: apps/v1
kind: Deployment
metadata:
  name: fag-database-postgres
spec:
  selector:
    matchLabels:
      app: fag-database-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: fag-database-postgres
