apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: fag-istio-gateway
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      hostname: "www.dev.sklrsn.in"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: tls-secret-istio-order-gateway
      allowedRoutes:
        namespaces:
          from: All
    - name: http
      port: 80
      protocol: HTTP
      hostname: "www.dev.sklrsn.in"
      allowedRoutes:
        kinds:
          - kind: HTTPRoute