apiVersion: v1
kind: Secret
metadata:
  name: tls-secret-nginx-grafana
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZXRENDQTBDZ0F3SUJBZ0lVSkN0bmQ4MXIrOTlx
    TnBqSnZTNzJXcDdsWGpFd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0lERWVNQndHQTFVRUF3d1ZkM2QzTG1k
    eVlXWmhibUV1YzJ0c2NuTnVMbWx1TUI0WERUSTFNRE15TXpFeQpNREF3TmxvWERUSTFNRFF5TWpFeU1E
    QXdObG93SURFZU1Cd0dBMVVFQXd3VmQzZDNMbWR5WVdaaGJtRXVjMnRzCmNuTnVMbWx1TUlJQ0lqQU5C
    Z2txaGtpRzl3MEJBUUVGQUFPQ0FnOEFNSUlDQ2dLQ0FnRUF1UmtHK2x3aEJBOHgKK05IQzQxcDc0c0Nv
    ajhuNldMK0k1aVdzS1pCRjdnZ0dsUkllMlNzNmJ1YU5jb2VqOUhydXFLSzVoc25ZVHpRRAoxRVA0QVJJ
    RmcwM0F5UzNTODZqSzM5TGJidEVVb0t4dXNvaUZjNlo3eCtXSDZNR0syU0padEZzYzZaTnlaMmU2CnF0
    aEYwMUViMFRTbkpkcHdQZDNSci9udXk0RWdTcDVlelYzUEZTM2c0dzJLVC82VHA1RExEcnc0U0cyQVdx
    MkYKa2RORGt3L2RCekpVc2N3U3R3dVpjWHA4azBCZ25lcWU5dnlWV1hXVFRkOStnNjVzV0VaZXBhQkt5
    VzNSSkdEWQptVEV0Rkd3TWdEaHNmV0l0dW5WajliekpjU3dIZTJrVXNKMEhXUDdNSkNudS9ES2pmUHVm
    aFduU3E4a3BSN0oxCndPdUVielJWVmIrdDMvQlpOTkdVSWRRWWVCWWxoNnhyaVZQV0RkdDdvY1pCeHdy
    SzFmNXVubldvSHdrU0xPeTAKQnJEdnZ5UVBjYjZOZEpsRkR0SDhyM3RKZmRFMFFZMmI3NDFyTEFGaStO
    UlVVczh4anIzSU5abkEvSXJQUVM4KwpkckhSSjVkMlZVZTlJN0xEQkFMMzIvczhjaHVMRytzVHZiL3NH
    ZlVIdzdzRXBMU21pUHZyaXBwL2hWUlJlelNQCkljQzBYdHJQcldkbjhOS21oVzJhWDRYcWtGRnFNTVVV
    R21HY0lpVFpsMlZqZTMxM0huMkV1UWFvUWRwbDZzR04KQW5PMG1HMzdjNklURitVRXhtZHhITGo1cjNn
    dTFHMlFLajhJOFR5b3U0Z2lTUm1Oa1dRZ3FlcXdndTJ0OFU0WQpKeDEwblk0OHhjc2daLzQySUJ2dmZo
    N096cDlYRTVjQ0F3RUFBYU9CaVRDQmhqQWRCZ05WSFE0RUZnUVU3NU5XCjdhbXlMTG1sWmNVTnFHbXVl
    ei9uQzFnd0h3WURWUjBqQkJnd0ZvQVU3NU5XN2FteUxMbWxaY1VOcUdtdWV6L24KQzFnd0R3WURWUjBU
    QVFIL0JBVXdBd0VCL3pBekJnTlZIUkVFTERBcWdoRm5jbUZtWVc1aExuTnJiSEp6Ymk1cApib0lWZDNk
    M0xtZHlZV1poYm1FdWMydHNjbk51TG1sdU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQ0FRQkU4RHZ0CjFt
    bENsalMwT1BHbWpwVUMzWElWN2Vmb1ZUOExnUHJ3T2V2NEhxbmM1YjZPdFNmZS9qOEFMaExjSFIxbWZv
    Sk0KbjNyeDhiNCtLUEF6RFhpKzIvSmw5WmtIczdncFRHcExkaEZYU2NLY0M0eTkvenJDUWhHUnIrVnRn
    RWduekh2UApVd3kxNWUxL3FDV3Q5UHo1OGR0MG9QVjQrRFV2MDhGRVJ5UkJTaUxzMDdFbGo3OGVwMG84
    MnZ4TG5DeURNWDFKCmVZWlNzYVlxbzNIck1GZ20rWGc0VWlFL1NRWkY3KytaYVJaQ0lJQm1ORFVldEJv
    TXFSZHZoN3o3Z1BubVo4SUMKcnpMQ0czYWh4L1lLNVJmN1JEMHJpUjhMcXBmdXRNMEtMNWtEWHdwSk01
    R1VVUXo4MzJ4WndKdzViNzh3MG1DRQpyemRaQnRLa2FUMmo5a3hsRE9ab0xJdmxYcTllU3JabE1xYld2
    bTFlVGszNGwwNVBRRW4yNktHcldnQTcwNFJQClBJa2d0aUxoS1ZHSUhwdDlzSDNrT0xRSWo4TTFLZ2hj
    ajVxK1Z4a01VMVY1VmZoWXRGY2dYdHpRQnp4VHVwLzYKbmRWRjNvbm4wVUg2UFNtai9nSm00dzZMa1d1
    b2JhSTlIZ3JmbVdFZkplLzZHcnppRjV1RGJkTHYvNkZrTnQ2cAo2dUxOaTZvTWlTYW80bGo2NDJmZ2Zw
    SnRqSjVYejBraVY0QjhJcnkzRkpoUVJnS05XMFFuQ3JUd1cvMFBmYUpxCnk1dWRVTXZlUWtBSFNzNXov
    V0NCcTlsclBlS0d2dmlGRGNVQXZYMGVHR2pmcGR1c1VxUTdaMVIxZXZuSEJITm4KT3dDMGZ4aDJxbWtN
    KzZXaTA0Q3VuMVRnODBzZU91L01JZjYyd2c9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVND
    Q1N3d2dna29BZ0VBQW9JQ0FRQzVHUWI2WENFRUR6SDQKMGNMaldudml3S2lQeWZwWXY0am1KYXdwa0VY
    dUNBYVZFaDdaS3pwdTVvMXloNlAwZXU2b29ybUd5ZGhQTkFQVQpRL2dCRWdXRFRjREpMZEx6cU1yZjB0
    dHUwUlNnckc2eWlJVnpwbnZINVlmb3dZclpJbG0wV3h6cGszSm5aN3FxCjJFWFRVUnZSTktjbDJuQTkz
    ZEd2K2U3TGdTQktubDdOWGM4VkxlRGpEWXBQL3BPbmtNc092RGhJYllCYXJZV1IKMDBPVEQ5MEhNbFN4
    ekJLM0M1bHhlbnlUUUdDZDZwNzIvSlZaZFpOTjMzNkRybXhZUmw2bG9FckpiZEVrWU5pWgpNUzBVYkF5
    QU9HeDlZaTI2ZFdQMXZNbHhMQWQ3YVJTd25RZFkvc3drS2U3OE1xTjgrNStGYWRLcnlTbEhzblhBCjY0
    UnZORlZWdjYzZjhGazAwWlFoMUJoNEZpV0hyR3VKVTlZTjIzdWh4a0hIQ3NyVi9tNmVkYWdmQ1JJczdM
    UUcKc08rL0pBOXh2bzEwbVVVTzBmeXZlMGw5MFRSQmpadnZqV3NzQVdMNDFGUlN6ekdPdmNnMW1jRDhp
    czlCTHo1MgpzZEVubDNaVlI3MGpzc01FQXZmYit6eHlHNHNiNnhPOXYrd1o5UWZEdXdTa3RLYUkrK3VL
    bW4rRlZGRjdOSThoCndMUmUycyt0WjJmdzBxYUZiWnBmaGVxUVVXb3d4UlFhWVp3aUpObVhaV043Zlhj
    ZWZZUzVCcWhCMm1YcXdZMEMKYzdTWWJmdHpvaE1YNVFUR1ozRWN1UG12ZUM3VWJaQXFQd2p4UEtpN2lD
    SkpHWTJSWkNDcDZyQ0M3YTN4VGhnbgpIWFNkamp6Rnl5Qm4vallnRys5K0hzN09uMWNUbHdJREFRQUJB
    b0lDQUNzYjdKZWZvR0xoSlJyVnc4V091OTYyClR5dlo5eS8zUCt1V0o1QXdsVkRZVnF3ZVljZmpmUUw2
    T0VSTjJmNGxLWE5tSHI2SlFSTkZRb1VMNVhWZVhLRlYKbVFwaDNVazViVEtPMmVObjE1MktPMmZpU3U2
    Qi9qOHlzcUlmZlhhUHZRTzMyclo5ekQzUUYxWVY4OEZCR1REeQp5ZUVUakdPa1IyTnNXdFRUdUpFWWJH
    ejVKYk5Ca2FoZjdYQXZFdldLVC9pWkZxU3J1Q0ttV2o3NXpMbXlEcURQCjlKREtQaXVhakh5MDhkR2J3
    MFRVTVh6Rm5BVVBVS1RvNGY3S1AxcVozUTVIRkZQd2V5NjFUWXowT3BNUWpTTEoKd1Y2OFlIa1dRUmNw
    Qm1PUXhSZFZoR2VUMHZQRHVBak9LV1pjWnQ1RGZrWWt2TmVjakx3eGtLSkRWLzlNV1hrdQpkUzkrQWUy
    d2R0T1NQWGRENzRhU1MvU09EaXNkOHBxNDVBS1M2WWU5alFmdVdjcXl6VEF0ODlSK09VNnJvdjFhCkVn
    YkFISXRYeitEN2t2c2pTMUtOOVRXbHhnMVp0QXJtdWpyRWZnSjhhc01GVGRxUFhveVNvQWJ2ZjUrdUYx
    MFAKOW9UMjhRUWdBNVNaSDFxQ1BqUFhZUWJ1OVB2cnBGcTZTYmlMK2FPdGJMc0tXSlFGS0ZsRWlMMHky
    VGpqTHFZSQpFZlpyNWJmZkpZREwzWDdqYVhyZk9wRTdrOCtzZFlBZnRSWXUzT0ZwZGJDMm85SFN0TzhR
    bVJZRy9Ka0c3Tjd1Ck1GUnFZQmJFaTBTb2R3N0F1aE9CMXNXc1ZwcC9XLzJYWXN0K25sNDU4VGhoQklV
    UElaM2hteDRIRmNpbWl6SkIKaGhPbTRYOE9BK0dDWUgzWnU0eTVBb0lCQVFEMlI5OCsrcVRrRkZKMlBM
    TEV5cUxpTytpYmdzUmw5aWxuS3dtRQpVbGRwL1ZvUkR6aUNJc1piU3JLYmVZaVFyTkxyWVpVbFpwUmtH
    eUM0SEhJdU5DKzlyUzNqc0R3SmJDZlNWb0NPCjF6YzFMTVd2VXdqNHpGUisvcGpFSGQ5ZjMzT0NrM25k
    UnRMYnNzMEVyRFlRbzBHcnNWc0M5U25DQXpUME44N1YKZUZiMXdFNUNaZkN3UTN4QUtBVlI1R3BDNFFD
    VXhSVjhRNDM5VkV2YUxNamp6M0JSWURldysyUVZNMU5hYUVPcgo5eU10N29Ebnd2N25IUFJEZysyYzJo
    TDM4cTlDMEdqSGE0QmNmWk1UZG1vZGxQSHNzWFVrSm12cis1ckxHSGIzCk1WRGx4TGwybHhjNTljTGVF
    dUlPSnc4S1hXdmpFek9saWw1UkJpMysvTnIzQS9SNUFvSUJBUURBWndqM2MrSnkKcldkNndZNVZFdFVn
    ci9oTnJUVVVQNHR6SUtVU3JMN0QzRitxa1FSTjVUWkRIcEZvN21EVFR5WDB5TnFQcmplcgpxRHY1OW1H
    L2haUFpldG4vNEY3WUlmR29qV3BKUXpqWGpyRUQ2cTNSOGRGc0w5Y1g3bXJVdmg0VjErQXpmaUx1Ckll
    SzNFTGJyMjJvbWV1U04wZDJoYWtZZ1I2SjZudDROeHN3RlFLRFFPZDFMa1NOTXJyd0Y0Nkt3Vm1LRGwr
    QzUKSGVaL1lmMWlwV3dpcTJxUThkMVQrL1lNcDYybzErdlhZMldra1hHaWhmbVlPUFNBWm1pRlFhOTIr
    dXhTWFEwYgpuUjNLUDVFaU14b1A3Qi8zV1VDMXNjaHZpNG1zRFg0M3htQ3IxYUI1QTY0MkxJRjEvQXBu
    bU8zRDJoamR1SlNPCjZSWU9JQ2Z1cEtTUEFvSUJBQnRlWTFYSlh0ZWwxb0FqUUs2VDRrUUg2bEtWMXFP
    S0ZwSExlNVJEM2tqK0NhdEoKcUxyMWlGdU8wb2hxbWgyUnh5SzNSbTdRbG44RmNMNWxFdDlGbDJTWndU
    YkRWL2lvRjBqTnFoMjFsd0lHeHJVMApJaFFjQ092UCtVUWFHYis2d2tocGdTcHcrMi9Fei9uTDlYb2wy
    bDl0SnpNTjhhVUkzREtqblEybUFPdndnZ0hvCitEVnVXbmw2dVJTZnNKdGNDOGQ4bTJXaTBEMnR4M3dv
    YSs2OUY3dERXUTBHOHRsVVNkZ0xMRElKRmRTOTQzOWQKOFJ2WDRPRTc0UVVFU3dWWTU5Y2g5L0xwWkd0
    aTNSeFZsWGRTSFF4enNCUGpYU3p0V2dkbDRacVkxV2VqVkFUMAp4M1QrZGJoZUd0Yjl5ak1acktxZ2NL
    WGQyWnRoZDIwVnhuT2E4ZWtDZ2dFQkFJNXoreHlUelliUXdyd04wUjlGCitVemhYUHZPRVcyemVzRTcy
    MXlQVUJMZCtHcm1RZ1NXZisyRUZXOVdoNVFNbHZLOVA2MS85VElBTnAvay93eDUKanpWSGsxNnpOaVhh
    US8xaTd0M2RpcGwyeWJNM3I0aXcvVGlYMXk2ZDFMVTlLak5NQ1hDMnBKQWh3S1dBRjU5YgpiaVdkZWRs
    VEdFQnAyaEFPV2N0bUVzeXFjdVkwcXB4aEsyckd4QmNEakt6amxOSHdzN0h3NG03Tko1c0s1enVCCmRT
    WGFPdVdrWGhYUGlLWm9BOWp1UFd6VTZDM0hqaFlpRWVIVjBabTd1UWxvejh4TkRtb1JBU0ovMnMyaThR
    Y2MKUk9DakdDdmdCbHhBakVHaVU4VnluQkFacmZ1c0NNdHdvU3oxR01sTldqckg3TXJFa1FLZ3BrV0Zh
    RkgvRnZISApMeHNDZ2dFQUgzcjA4U0tjRUlhUlZCL3RJZkJUMzhBanJZeVAzL29FeEkreG82ZmMwTGp4
    OVJpKzNGUURncHVNCnR1QkdmN1NzMkUwWUNRZEtzQ3NZU3dZcVFVcGxKcGxucVBWbVVQSlIrQkwyYk90
    T1hxN2N5b2NvVW8vR2JUaWsKNk1pQWJxczNzem9RbVJnS0ZncGpYMW94WWwvczhuTFEzN3k5REdFdkwy
    T1NYdUZsM2JqdmdHQU81c1hpZ0ltWgo4UFVLM0o3eW5aOHNpOHU3SHllUGNCdUZJbHYzb05kbnpLQWZn
    bWpMWWYrb3lIUE5XN2dvR2EwLytnbFhQNW83ClAzUElubHhEOGlYaVFsTHVNRGl2Qkt5VTRjSjJ5dWFW
    Q3paSzcya0U2alRLNThYeHNlYit2V1VXRVlhRTF5ZW0Kb0JtcEtZWmVOSTFZWll6SGVsWDhpV3JUaWJN
    QTRnPT0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
