apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: fag-istio-gateway
spec:
  gatewayClassName: istio
  listeners:
    - name: https
      hostname: "www.dev.sklrsn.in"
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: tls-secret-istio-order-gateway
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              kubernetes.io/metadata.name: default
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: fag-istio-http-route
spec:
  parentRefs:
    - name: fag-istio-gateway
      namespace: istio-system
  hostnames: ["www.dev.sklrsn.in"]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /order-gateway
      backendRefs:
        - name: fag-order-gateway
          port: 8080
