apiVersion: v1
kind: Secret
metadata:
  name: tls-secret-nginx
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZOakNDQXg2Z0F3SUJBZ0lVRzJvZ1g5K3Y3UThh
    YW1YMnFHWUMzK3pVM2FJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0dERVdNQlFHQTFVRUF3d05kM2QzTG5O
    cmJISnpiaTVwYmpBZUZ3MHlOVEF6TWpJd056TTNNRGxhRncweQpOVEEwTWpFd056TTNNRGxhTUJneEZq
    QVVCZ05WQkFNTURYZDNkeTV6YTJ4eWMyNHVhVzR3Z2dJaU1BMEdDU3FHClNJYjNEUUVCQVFVQUE0SUNE
    d0F3Z2dJS0FvSUNBUUNQT0lJeXNQZjB0TUJwanVvN0hyUzdyYmM2TlJCMXVpcFAKTisvRXJYT25RV3Ur
    T3Q2QmNDeG1uZHBJNG1OajUzKzRYYkdTZURsMThWSGdDazZGaWxrdmVLSStockszSTYrWQpjOUtlQzdo
    VmRxSkJVMHlkSFpiNHdQTS9zc2VKRVhhYlFpcnd2eHgrSm01RzZNcm9DTk1mTGR4Y2FZeGhRUnlmCmpP
    UUs5L0JXeDZqRk1wSUJ2SSt6NGdhTVIxSjNWYVpJeUlmdzBET09waDE5enpMMWpCaDdGdkh4SHdnWCtG
    U0wKcEkrWW5LbFM2L05mWFdJQmw5b044c3FyTFVrLzc0UEtLMmRaTjMyc0tIRUJyMHgvT3lRS3ROSDB3
    c20zWTI4NgplTFJ3Ykc5Yk1wdlBGdXgvSUhyaGlIYmlxNzRaSHQ3ejhtSHpqaEdBRE1EZkR3KzVXNFJB
    SlIwT2x4cDRLeEErCkQ5TEJQZzlGVG54MXNhTGMrQXl4dCtScE1Rc0hmcCtDT3VpcFViMVNlNmZRQmFn
    bDdIL2hZZng0MkVmVWpDSDkKRXBkS3F0eTZJTyticWh5dFpKQ3M1NEE1MHRPbEQvcWZXbnhodEg0a3Zk
    MEVScStWa3hyd1A1QWpURE9DVURucwpLczNYaEpHcW5PSnp4NFJUL1Vnd3BmQ2o0bURnSW9obFZtZ3VL
    Szh3NzJuM0NBNzBZK08ycnRMcndDQysvb0lOCjZqK2w3MTM3LzFEQXpCM05KREJXR3V4ZlUrTS9YbWlT
    bWtPeXJDMEo2TS9QNkpiTmlzYUFSd0x0M3VTa2ZvVTYKdXJwc0d6WENCVGZGUGYwbkRIUkJNa1RibVY3
    ZFBSVTRMWCtvL0tCczY4NSt3YndybGpwZmphbFdpREpEY3JLWApDQzUvOFA5RTZ3SURBUUFCbzNnd2Rq
    QWRCZ05WSFE0RUZnUVVicmtNSWJhT0M0UHpwSG0xSUNJdjg1aW4rRVF3Ckh3WURWUjBqQkJnd0ZvQVVi
    cmtNSWJhT0M0UHpwSG0xSUNJdjg1aW4rRVF3RHdZRFZSMFRBUUgvQkFVd0F3RUIKL3pBakJnTlZIUkVF
    SERBYWdnbHphMnh5YzI0dWFXNkNEWGQzZHk1emEyeHljMjR1YVc0d0RRWUpLb1pJaHZjTgpBUUVMQlFB
    RGdnSUJBRVFIQVVWUjVxUDFzbHlYU2o5ZFUyamV3MzFPVmpzbVBpNzBrdzRRbnhVcE8wOUJMamFDCkdw
    MTN3QWRnNXFvbnlVRlJXb0x6OVNSSWtWL0t3dUI2OWxxZXd6djJjVGFIVE9XVXVIbXdWRG91SDFOZ3hU
    WE4KUzdzS0tRS1VSWC9ZV050ZVpxRVIwcUFDLzB6eFM0M0wvMjBwbWJJaW9mMmJVbDA2eGxDbTFBV2NP
    eFQrOFVFWApoRE9DZVJKelFnVEY3dWovU2xCdVlFTkVJVXMySFROZGNueFVRTzRSUjB5ZUNkb2RkTnVT
    SE1RWExOLzBkZnJECjJjaGkwRkNsQlBFcTg0U0w4MlJiemN1cDQ5b092RzhuQWtVeHNNaURjNXAxNHVu
    VDZ2cnVOUFJLOUtpTDMvUlIKcHZBSGNScTlFcEhTMGpVSTB1V1ZQdmVYU0c2Z3c4Y0pQbHdPWE5ucExs
    VXhJRmxqaG9Ib1hCWXZsWEk0ek1JTwpmY1AwVGk4ZVZITXRuV3YxcWRFZEZuUEpTamgwSzlCUnBaVXVk
    dFAvTkxUdWU2Y0drdEhvejhZZTRVNStJYlcyCm5TTG1wclk3ZkR4d3VqUVE1bGVXYzl4cXlhaHI0R2pk
    Wlc5anVCMUJzY0gwT2hiQThjYVhBVS9HczNuc250YnQKaGVzdUxaOG40NElUZXkrQzJoUGhxbUhoVTFa
    UDczVUN4a3VIYmRNSHhDcU1zZ1ZmRURDQTJiODlDRXhmOVZ0dgpZekRVc2ZDVm1pQzJCTCtFd3YwMy9S
    cmFWZThTZjBuWjJ2RVI0S3JjbUhJQXpJMkx4RkM0Mms2MXQ2aHkxYmVRCkliSCtEbGpjWG5PdGllNHcy
    cU52ZzRubkZ3VUhxeGw1N0g4TExNM0hxYXlnY1R5Yy8wbkxFUVJrCi0tLS0tRU5EIENFUlRJRklDQVRF
    LS0tLS0K
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRd0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVND
    Q1Mwd2dna3BBZ0VBQW9JQ0FRQ1BPSUl5c1BmMHRNQnAKanVvN0hyUzdyYmM2TlJCMXVpcFBOKy9FclhP
    blFXdStPdDZCY0N4bW5kcEk0bU5qNTMrNFhiR1NlRGwxOFZIZwpDazZGaWxrdmVLSStockszSTYrWWM5
    S2VDN2hWZHFKQlUweWRIWmI0d1BNL3NzZUpFWGFiUWlyd3Z4eCtKbTVHCjZNcm9DTk1mTGR4Y2FZeGhR
    Unlmak9RSzkvQld4NmpGTXBJQnZJK3o0Z2FNUjFKM1ZhWkl5SWZ3MERPT3BoMTkKenpMMWpCaDdGdkh4
    SHdnWCtGU0xwSStZbktsUzYvTmZYV0lCbDlvTjhzcXJMVWsvNzRQS0syZFpOMzJzS0hFQgpyMHgvT3lR
    S3ROSDB3c20zWTI4NmVMUndiRzliTXB2UEZ1eC9JSHJoaUhiaXE3NFpIdDd6OG1IempoR0FETURmCkR3
    KzVXNFJBSlIwT2x4cDRLeEErRDlMQlBnOUZUbngxc2FMYytBeXh0K1JwTVFzSGZwK0NPdWlwVWIxU2U2
    ZlEKQmFnbDdIL2hZZng0MkVmVWpDSDlFcGRLcXR5NklPK2JxaHl0WkpDczU0QTUwdE9sRC9xZldueGh0
    SDRrdmQwRQpScStWa3hyd1A1QWpURE9DVURuc0tzM1hoSkdxbk9Keng0UlQvVWd3cGZDajRtRGdJb2hs
    Vm1ndUtLOHc3Mm4zCkNBNzBZK08ycnRMcndDQysvb0lONmorbDcxMzcvMURBekIzTkpEQldHdXhmVStN
    L1htaVNta095ckMwSjZNL1AKNkpiTmlzYUFSd0x0M3VTa2ZvVTZ1cnBzR3pYQ0JUZkZQZjBuREhSQk1r
    VGJtVjdkUFJVNExYK28vS0JzNjg1Kwp3YndybGpwZmphbFdpREpEY3JLWENDNS84UDlFNndJREFRQUJB
    b0lDQUIzT2xXNUdYWHlNeDhUUVRSaGJ4aUtQClAyUjZXY0FlckNLTGtqZWRIOFpOKzhYK0M0UGwzQi9K
    TjM1V3UzZTEzT042Z0hQcTJJNmUyRHJuK2pxWnRnRUcKdXNHSG1CYzhjcFdvZVV1U1JkMW5rTkpHcTFu
    QnFFT0NLTDMzajhhTG4yTWxyTGtwRlIxK0V4Sm43WjdJQTJSbwpUNFhlSTZ5ejkraU8wb0VqNDkyenRR
    REJpeGlZYlZIek53aW42VlpUdVlWSlV0MS8vMUx2YUpEZitBdVppaGpJCkNEZDJEV0dydWJETVlXUlNL
    bjFMQlA0eWVheTZOVlFVMVRBMS94b3kxM3RTZURKZHRhYUlUaWliR3JFYUZtQ3kKREVaRDZlWmtaK2hE
    NmMzQ0M1VHYzZlNHSVZjOTQ4VWZlUnFvd3FvSXZqOElFWEcyZmhibjBKWTcxTHB2ZlFEcQoxNjNxeUtC
    RGtSR1A3T1ZiSzRlZjBBRjAwUEZJNklpTXBBbCtWaDArZkxmaWVmZVgvNnlhZC9qU1kxcjVrbjY3Cks1
    UklBMWFzbzNET0lUNmxmZFpYN2ltMHF2VmVTeno4QTNIbVl3K2ZHa1RRWk1WcjY4SG1kZEplb3k1TE1B
    M1UKck9qNDVsSVByeFRTT2hLL0tOSUNiVUs5bWhNNW5Xa2pJemRkd3daWXJTaUU1aEo1cjRvTE0yVlgr
    Y0pST3FNcQptblJIcWFlRmRpeFY4QUVwSG16Y3ltUG5wUVprWjBPZ1U1aTJTdDYvVytrcGo0NFdIVTdj
    U3JzUXh4RDNFZ1VFClNVMmNuTjgyWEFiRzAyOTFrYzZTRHg2RnBMN1I2NjBYT09GUHlpM2xwbFYyZWlY
    cDZEYksrZ0NRSEFvdnFmcTQKSFZGaWdPcHFuS1V6eDlKSmUzZkJBb0lCQVFER2Jlc1dEYlR5cWc1ZkRt
    WXRYNUlzelQxUFBDTzdjSnJDYktuRwpLRU9sU1hDU0lRcFZ5WHY4cDJPR0dONDJZSkNaR0x4WVRBWmlZ
    Vy92U1pZVS9xeHJudW9sMlRvQkdkMDlmWFFyCi9yalYvWlVUR0xwUnYwV2Z6OThZODFaN3pWYkNtaGNU
    WlJpRzkrdEtEMGtHNDV0MzQwY0lSVUswcGJXV0hneVEKZTNOVDdMVjNxZXo5bENSVDNsOW01MjBkV2Rs
    b0MxeWtJekY1eE11SVhyd24yN0RNNUpSc3B1RnUxMUtyaVB4awpTS0hTbFJobzEveVlFVmlxb0EzTytJ
    NDRiK3dTdnVBdVdGMk1Pb3VqaVJORmF1amNzckl1eWJBRXRuZEhzeEFGClpkOXp0UDVkdzNEU0xXdXdt
    d0p2K3kzNEh0anVuL3h2bmhmaWVrSFJNTEkrN29FckFvSUJBUUM0eGdxWktzK1YKNGFNWGh6WGF0OWx1
    eHBlT1YyZjZwa0QvaVNUaW5JQndLaXV3TWtHQmVHSDhHSUltcGNTYUVDNmFiakkrNFl0QQpnZWJDTmVI
    aFNCZWFtTzdNK0xpaDBCSkhybWd2WlZUWGlhR0xjYkpRcUlWZzdqbjV1YmJEeGtQbHFOa1cyMmJ4ClRJ
    RXRWN3NsdnUzb3lrTUU0Z09VS3dWRVBPT3NOSkpxbU95ZGJOL2RiZ2c2MjVxUnU5WHZ6R0k3VHpSejZr
    WUkKMTJPN21QTnhiRnBsVkNvQjRpOWFiK0lHU1hUVExUOWpHbzRnVTlXVVE5YjU1TTZMTkswc2swSHNw
    L0d3RnFMZgpiS1RZY2FkWWlFZ0ZIaTVoMDV5K1U1QzEwZHB1TmFQU0Q4VXovMHJqQ2tVYkYxYzZ6Q1N3
    M1RJM0Y5QkFGUGxiCkVLWTJ3YUQybXV0QkFvSUJBRHZjank1QkJsU3F2dGtvWStUT1R5L2EzdU1YZG9R
    bWpWbVlKSU9XUkFvS0pMN0EKM3ZoUVoyb3FLVmtjQ1hXSUhqZEJnaGgxSHZ2dy95N0dHVlBPSEwvKzJn
    NS9BUU95Qk05M0dHUHBYV09aTTY3bQpKOWRmaDZhVnRHMDNnK0NuYXNRY2JsZTRpUFMydURISWVMUnVW
    OG1NTkRLbmlsOHJHcVBsL3M1Ym44Z3l3ZkFPCndHTWpuTzM4U1BXblhZQ2NTWDBjNkY3UUN5MzhFNWJa
    VlpRRXI4cXdMcUswbVkreHY4dmw4SlprWHdWRFczRE4Kci9ORVVHWnhFSmxlM0xEait1a1EwbHJJNTdm
    Vk5ha3BRam9QN1o0ZS9xZ2t5a2d4cjd4ZXBiZXJLd1VpRmhhOQpUanpwM1BJVFlXSGMrZG8vbkJ3cEFh
    TytvdC85Ri92KzM5Y2lacThDZ2dFQkFJcUdScm5RQTdMOVo1VWpGRGYyCmIzZUNRV3RBa2o2eTE3WDhM
    b0FLRHF5SW9ScEdneCs2amRNKzJJeDY2S3NNQ0xSVWV5enpVTCs2NDdLa1RNVGwKbEhTZHhTSThNY2Qy
    UTg0anJnNGliUG51UUFOWDZQUlpjeTFaVEhPeFRKajNrajJpV2FhdU5ENGhPaE14VzZnUAp2VE15T0E1
    NEYzREUwL3oxblVha1gwUzFnMmIra2RMalJCNUVOMXljc3VaRmx6dVp4TnhHUGQweEJaOUdLdlRVCjQr
    eGxyZHlkb3h5dEZvbmFGbENmOG82dEFQS3hoMFRSbTJEYnJoRmxHNU40andzS1djTEhKYkpWTkR6azhD
    NEsKZGR3SVpZT0g3MUl0T2lkbHZkbTBNeTR3RG90T0VPbW44R2xBRlhDS1RkT2U4WittSmNWMU5BQ1d1
    ZFlCVWxpdgppa0VDZ2dFQkFLbUJyUkFBNHQrWnN5Y1hSdWVvd0pKMDdIa2laN1hNYS82V1FZNGJXQWRx
    SzFRSkNDNWU1L2hMCndWdENQZVpXdE9rckF6ZlRQZ2N2cGUrMUcwMlBieVBvSXZ3cGpkN2xpRzZ0cVd6
    dWk5K3E3M1FIZ0lCUjR0RWkKRG5tY2R2eHZJaGZqN1Iwc0pLbXRxRE9CVVE3ZXBTSFIwaFAyemk2d2pI
    VE9XZEFUK1g2bHZGM3RnMlorMzFSTQpqNHhIR25NUFVxdmYzMUpkMFRIVk14Yy9EcFFic25aalpDZHgr
    NkUxTHpxbXZOVWphRFJqeitUbVh4VGVHZXFvCnRCTDVPb2NrazJhVGlVdWdTVkh2VXNYU2paMkFWYTEw
    b0syVys2RlN4RnNCdEM3REVid0VIZ0pKQ2ZFN3RMZmIKaXJsNEthSFF4WVR6R3M5ek9EbktzeDgzOGNq
    WlV1MD0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=
