apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Ingress
      name: nginx-ingress-loki-grafana
    path: fag-ingress-grafana.yaml
  - target:
      kind: Secret
      name: tls-secret-nginx-grafana
    path: fag-secrets-grafana.yaml
