// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"

	"github.com/google/uuid"
)

type Order struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Quantity int       `json:"quantity"`
	Created  time.Time `json:"created"`
	User     *User     `json:"user"`
	Payment  *Payment  `json:"payment"`
	Shipping *Shipping `json:"shipping"`
}

type Payment struct {
	ID      uuid.UUID `json:"id"`
	Amount  int       `json:"amount"`
	Created time.Time `json:"created"`
}

type Query struct {
}

type Shipping struct {
	ID      uuid.UUID `json:"id"`
	Created time.Time `json:"created"`
	Address string    `json:"address"`
}

type Subscription struct {
}

type User struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}
