apiVersion: apps/v1
kind: Deployment
metadata:
  name: fag-postgres-metrics-exporter
  labels:
    app: fag-postgres-metrics-exporter
spec:
  selector:
    matchLabels:
      app: fag-postgres-metrics-exporter
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fag-postgres-metrics-exporter
    spec:
      containers:
        - name: fag-postgres-metrics-exporter
          image: quay.io/prometheuscommunity/postgres-exporter
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 9187
              name: metrics-port
          args:
            - "--log.level=debug"
          env:
            - name: DATA_SOURCE_USER
              valueFrom:
                configMapKeyRef:
                  name: fag-config-postgres
                  key: POSTGRES_USER

            # - name: DATA_SOURCE_PASS
            #   valueFrom:
            #     secretKeyRef:
            #       name: fag-secrets-postgres
            #       key: POSTGRES_PASSWORD
            - name: DATA_SOURCE_PASS
              value: "postgres"

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: fag-config-postgres
                  key: POSTGRES_DB

            - name: POSTGRES_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: fag-config
                  key: POSTGRES_ADDRESS
                  
            - name: DATA_SOURCE_URI
              value: $(POSTGRES_ADDRESS)/$(POSTGRES_DB)?sslmode=disable
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: fag-postgres-metrics-exporter
  labels:
    app: fag-postgres-metrics-exporter
spec:
  selector:
    app: fag-postgres-metrics-exporter
  type: ClusterIP
  ports:
    - name: postgres-metrics
      protocol: TCP
      port: 9187
      targetPort: 9187
