apiVersion: v1
kind: ServiceAccount
metadata:
  name: fag-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fag-role
rules:
  - apiGroups: ["*"] # All API groups ("" includes core APIs)
    resources: ["*"] # All resources (pods, services, nodes, secrets, etc.)
    verbs: ["*"] # All actions (get, list, watch, create, update, delete, etc.)
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fag-role-binding
subjects:
  - kind: ServiceAccount
    name: fag-sa
roleRef:
  kind: Role
  name: fag-role
  apiGroup: rbac.authorization.k8s.io
