apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fag-role
rules:
  - apiGroups: ["*"] # All API groups ("" includes core APIs)
    resources: ["*"] # All resources (pods, services, nodes, secrets, etc.)
    verbs: ["*"] # All actions (get, list, watch, create, update, delete, etc.)
