apiVersion: v1
kind: ServiceAccount
metadata:
  name: fag-sa
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fag-cluster-role
rules:
  - apiGroups: ["*"] # All API groups ("" includes core APIs)
    resources: ["*"] # All resources (pods, services, nodes, secrets, etc.)
    verbs: ["*"] # All actions (get, list, watch, create, update, delete, etc.)
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fag-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: fag-sa
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: fag-cluster-role
  apiGroup: rbac.authorization.k8s.io
