apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: www.dev.sklrsn.in
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: fag-order-gateway
                port:
                  number: 8080
            path: /order-gateway

          - pathType: Prefix
            backend:
              service:
                name: loki-grafana.loki.svc.cluster.local
                port:
                  number: 80
            path: /grafana
  tls:
    - hosts:
        - www.dev.sklrsn.in
      secretName: nginx-tls-secret
