apiVersion: v1
kind: Secret
metadata:
  name: tls-secret-nginx
type: kubernetes.io/tls
data:
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZSekNDQXkrZ0F3SUJBZ0lVREpSa0tEekZrK3FQ
    Q2YxOGhEbE5nakl2MUxNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0hERWFNQmdHQTFVRUF3d1JkM2QzTG1S
    bGRpNXphMnh5YzI0dWFXNHdIaGNOTWpVd016SXlNRGMwTURFNQpXaGNOTWpVd05ESXhNRGMwTURFNVdq
    QWNNUm93R0FZRFZRUUREQkYzZDNjdVpHVjJMbk5yYkhKemJpNXBiakNDCkFpSXdEUVlKS29aSWh2Y05B
    UUVCQlFBRGdnSVBBRENDQWdvQ2dnSUJBS2ViSjVUaThHdWh1a1owbk53UlZvSFAKbXRrSzNoSzhYbU80
    MEozNjQ1Q3h2ays5VlM5Nnh1Y3lCbFpNZnlJNDdNVGxwQXd1bDdRODROM1NHME4xb1RGWQovRzZ3TVpq
    V2gzTkZub0lrbytZcmQ5SElRMURkbE5OVlM5ZjViQ3FRZURoZkRzMTgrMHRpdUtuRVlMVHFQSjV4ClVX
    N2lSaEVDNjdnRi9qV3d1R0p4cmZ6cVJqM1daNFZIRWtNUEtoRXhTcDQrby81MWhnOStaVUdTUzdEbklv
    R1QKeGdXck1SU0RHVVlCTUdQeE1id0xkM0pmd2llVllpZHNMY0R3b2l3VW13Mk5Yb1VBZFNzTmxPZUF0
    T24ySGJlNgozZVpLZVY2VWNFVjdESU5RNE5Fak9SdWl6Nm00M1JQc3JyT1U5TnZsbVNlbyszSUlBR3pi
    M0pLdmZtT2xPd1p0CncxRlU1TngrQ3p5KzJoRU0vNFVrRGdNM2tqYUkxU3FlQVhWSkZpelljMGNWc2Zs
    amlyYXN5cWU5T0F6ODFOcU4KRnNqQWNUTUFiaWVaWWVYa2MvYjdlN1NsK0ZtNlMyOVRkbm9uRjVUM2ZL
    SHZNNUhoaGlxQkFhZklHc3BoSFR3UwprWVdYUGphSEYxUDJqajdPeUNlRmJwNE1VZko2RElqL1JjZDVO
    UzFtT3ZKOWM3RGlmMHNwbHZnZCtUTUFQQXV1CnRBZGR6amVjSCtNVjAreG9uTkQ1RFdwZ1lQZjFBanQ5
    L3R0U0ZHZ3lySENXMS85NzJDUHpPY2duMEVGVXBra3YKSUhGeWJqSllUU0Vab2l0SXFCc1J6SlluRzE5
    OXpya0dtWFJUMTRiRkgxNXdyVUpGQm5kc2NFMEkrRWVkYmN3VQpFY28wZjdNd3d1dzlUSFdENDJabEFn
    TUJBQUdqZ1lBd2ZqQWRCZ05WSFE0RUZnUVVVMVJFNU9MczRrYlBWckxQCmdUK01WMUZwN0lJd0h3WURW
    UjBqQkJnd0ZvQVVVMVJFNU9MczRrYlBWckxQZ1QrTVYxRnA3SUl3RHdZRFZSMFQKQVFIL0JBVXdBd0VC
    L3pBckJnTlZIUkVFSkRBaWdnMWtaWFl1YzJ0c2NuTnVMbWx1Z2hGM2QzY3VaR1YyTG5OcgpiSEp6Ymk1
    cGJqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FnRUFkZ3gxMHg0MGhDVDhIZDRrOXp5TmxKbXFjRHhjCk4z
    dEIzb05oQnNWS2xzN3VXTU12TmxOUGNLS045dmJPTTJEejhONmdqWnU3dHFSdngvbzFYSUtXRUNlUVh3
    cHMKaVc4Y3RZaW5nc1BWM0ZOUlBkd1diem5lOURvUVcrUWFBSXJxOHdNSU1HazJQcnR5RUZCUmRydkF3
    ci9MWEhyRgpGbVJZVUVsRThZdkJVSGlaVjNHKzhzYzZHejlKMFVrL3FHUVYzemhRUjk4Z28rTDAvVnh1
    QU5PRlBBSEJPOXlPCklWb1p3Y1Y5SXlqM0xzR0JqTzhUSGhNMFBGYS84b29KTmlSbEhoTHNDeFQwRTgv
    VEl4NDF2MmVEaGYzZ1Q5MHgKeUtqUXcyQ3l2K0tSTDIzblJnQkF0UWZ3Mzc2QUFSL2VpaGRrLzVUQjFI
    VStmZlJKc2hlN1I1Q2k3bnVwa2FrZgppTGlSaGs3dERnWUxidlI4UzVzNkZ4THdXbDJwWFV0TTNxdFZX
    Q3BwSWM1UHJzUWtuNFNnbDVxc1YrUUZPQzRPCkFnRDZtSCtQc2cySzlybjZoM3l2K200Q3Z3algwdUth
    NmhEeURTZTlkK205OEVMUTcwV0FHM1JvbmFEN3J6R0cKVTRreVpUbE1pclFXaGJJSWtkeHhVUEozdERI
    QmFwc3F2eXRZOFF2QithZGlUTkx3NCtaTExnWkRhZkVUOVR1TwpUZDRzMk5kWnR5TW0wVWd4MTVjRXBH
    SUdwWmZCQzJhQnBJSDNFUjY5RWNMUWhtVEhaQlAyVjFRaDhrVldvSUNOCmtCeDdHVWVmR3RYM09raDBO
    THo1Y3p1azdRdlNwS0tFZG02TmgvWEJtNzF3NkU3V1lEb2F5bERLQ1R6QzFzaWQKWEFBRXhURStweG1v
    cGRFPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUpRZ0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVND
    Q1N3d2dna29BZ0VBQW9JQ0FRQ25teWVVNHZCcm9icEcKZEp6Y0VWYUJ6NXJaQ3Q0U3ZGNWp1TkNkK3VP
    UXNiNVB2VlV2ZXNibk1nWldUSDhpT096RTVhUU1McGUwUE9EZAowaHREZGFFeFdQeHVzREdZMW9kelJa
    NkNKS1BtSzNmUnlFTlEzWlRUVlV2WCtXd3FrSGc0WHc3TmZQdExZcmlwCnhHQzA2anllY1ZGdTRrWVJB
    dXU0QmY0MXNMaGljYTM4NmtZOTFtZUZSeEpERHlvUk1VcWVQcVArZFlZUGZtVkIKa2t1dzV5S0JrOFlG
    cXpFVWd4bEdBVEJqOFRHOEMzZHlYOElubFdJbmJDM0E4S0lzRkpzTmpWNkZBSFVyRFpUbgpnTFRwOWgy
    M3V0M21TbmxlbEhCRmV3eURVT0RSSXprYm9zK3B1TjBUN0s2emxQVGI1WmtucVB0eUNBQnMyOXlTCnIz
    NWpwVHNHYmNOUlZPVGNmZ3M4dnRvUkRQK0ZKQTRETjVJMmlOVXFuZ0YxU1JZczJITkhGYkg1WTRxMnJN
    cW4KdlRnTS9OVGFqUmJJd0hFekFHNG5tV0hsNUhQMiszdTBwZmhadWt0dlUzWjZKeGVVOTN5aDd6T1I0
    WVlxZ1FHbgp5QnJLWVIwOEVwR0ZsejQyaHhkVDlvNCt6c2duaFc2ZURGSHllZ3lJLzBYSGVUVXRaanJ5
    ZlhPdzRuOUxLWmI0Ckhma3pBRHdMcnJRSFhjNDNuQi9qRmRQc2FKelErUTFxWUdEMzlRSTdmZjdiVWhS
    b01xeHdsdGYvZTlnajh6bkkKSjlCQlZLWkpMeUJ4Y200eVdFMGhHYUlyU0tnYkVjeVdKeHRmZmM2NUJw
    bDBVOWVHeFI5ZWNLMUNSUVozYkhCTgpDUGhIblczTUZCSEtOSCt6TU1Mc1BVeDFnK05tWlFJREFRQUJB
    b0lDQUNKaG84STVObWZoMW5BWEFrbHJmaE1sClp1YWdnZE1XbElkQTFYeWV4M2s2V09lTEYzTWtyTElt
    OHlGWFVsb1BFdFRHSmJ1QkFFb3ZGZEt6QTdnNEpFK1cKNlR0OGhjUU1OOTluMTk3ckRMc056aWU0dk1S
    VkcrOHBKMlIvckJaa0tlRW9jTVVxM3ZMRkpzdmVkcGNPR003SQp3Sk51TThEUUdGSVkycCtoWjRWOE85
    eHVvMmVTZUl4Z3VxaUtidzcxVFZEK1dRNDlCZm5lSy8vQ05xZ3NsY20rCmFrZmw2T3pFQXRaM0xubkY4
    N1dYSlpMTy9XazR6ZGgzNnIvU0xQWTlhTndrRkpCVWVuU1JOZXN5WGdwRFhDL0IKRTcxbXFCU0VmeTVs
    a2pqS3liOWxDaFUyOWdIakkraXZLOXczVVc1ZFlDaEFWQW85aFhiUE9DVlgvaVdMTXJybQozRDNWTmNa
    bDJDRFpjdmxpd2xraFlRSGVWTk9sZXgwbTB2a0ZjbHpYTEFxS0VONWgwSmNBenUydXgweXkwaXMwCkpa
    SzB6NHc0d0tzVUVISDhEYWF6a0E3Qk00T3FmeUsyMlhRdkpwVU9VeGxqdTVBdVlCMXNXZFFwUUE0WUtR
    c3IKaXFCSy9RS3VjdmxlZjQwU1lOaXZUdmthVTlWV3J3WmdhNkF1RzVVMnJhZVVMWUVmQkxaeTJIbTRO
    VFczWVdvKwpvTkxPRDlmdTZrM3QrMVIrUFo5N3d2WDhzVktqeUU1UWlicmVsbDFMR2hheVZuNWZ2SVFu
    b3NYTElJVmpiV2t6CnZTeXFEUnl6bkFPdklENXAydU8xUFBTeFNqckxIbWJ6eWlNU3NzNEE4c2pCLzRw
    Q0R0SHU1VnlWK2tXeVJVSEMKSERpYUZxZ0hiSkxwTmdUVXBmTVpBb0lCQVFEZ3A2c0JBZkIrYk5tejFX
    SGw0NzlCUXM3ZDZzVCsxcytOYzRPWApyczluRHhYQjV5Ym9YaTZJdW1qRjl1U3BDazVVTXJLUSt1WWQ4
    NjJmaFlrK0F1eTdLLzlLVHhrajU3WnA4L3B1CnpUQXR4dDZMVUp0SElBNkRpRjAvV1BpQUR3K1ZXOHN5
    T2JaMFJ1T2psRDF3OVZUa2VvWGZXMjFhbVg0QlhaVDcKbE50T1EzMklLb2o3djIvZHBlaUZsU3lqVG04
    NmUrWkxGRVpRSTR2ZU04VUU0c3E3QVZzVyt3R21COU9xQ2tJWApTS2NRM1o0YSttUVZMaHF2N3NZdXdZ
    Q2xaUU0wU1Q3UERHN3hYbE4zZDJTMDhkdEdtL3BXTmlpS0ZpWUwxSCtLCk9JRDlGYk5mQjBSRmU2Ylkz
    UUJZR2Z0ekd5OWkydEs2N2RETGkxLzNSb1NEMUpENUFvSUJBUUMrL2NtbTdyLzEKL2doZkl1TndRVXNQ
    Qi91YU9rS1cwWUQ1Yk5zMTF5Z3I0bXVNRUdUdFlYYWVmMDBGRnM3UkVFUVREdU1WTStQQgpnM2FBU2h4
    L0pTcDNlMFEwS0ZMNk5Cek84VXFKbVRyTDhjeXZuNXkvbDZXZnNmWDRlQzA3QVBzTzlEdzVEWG02CmVW
    ZThmSnhFZVpxRnVzRkdiYktvVGVVZld0TkNyamhmUENiZnBJRnhUeWFPTko4czc3T2M2WjZSSFZvclBz
    Z2kKLzFRYWFoMzJWemJmdFRQNU9xSnk3bG1XVjk0cnluZHhtTyt5TnFuekljSFo4Q1RZbEdwREZzY3FM
    V2l2Zk03ZAp1Q2tZZ3ZxWlJEa0FzTjFhM1BWT2UzL1ZhVktPRm5ZclJYRmYrU2VTQ2JqdE03QkJzN3Jh
    U0xXajQrZW1TNW9LCjZDbm82c3p4K0lmTkFvSUJBRGEvUllJYVdlUkZYSXhock5qY05vaU40bUhjUzZP
    YTc3dVY4ZlN1Q2ljZ1d2b0UKL2N0VTRGdzdxVHJOSHc0K3o3WGZJUHNKMmJoazRPUG1JL3J6dFlNcmhx
    d3lPSHN5aFphdWVWSTFPTTkvRGs2LwpGd2d2UExvN0toWTg5Vm9uMFhGaGpGUXlFaytsMHVYVFEySGF0
    NVJ5YzF0cUtXMFJ5TTVHWXY4b1dJVnJGeFZ1CjRERVJodzVwMXc5dXVoRVdGUzhZY0pmTldoRS9pRjlm
    R0YxSGM0WTlIMWlyVk15RVRjVzdlRDI2VzlSVlhhbFAKYWNKcm1OOVUvZ0Q0OFFQZGFQbDkvQXR6Q1Rw
    UzlWNUF2MDhGUFoyb2QwbzVLb24wT2ROYU5yYVZiSUhBbnhUQwpiWlhOTzJ6UDlyeUJvSEI5cUgrYnVn
    MEoxWDgwK084R3hWWm5IK2tDZ2dFQVVOdmRYY0ZDb0FDMnhxQmNyZy9XCm1UeUY5dHVuaVhhVkpnUkNJ
    bDgrOEtWaFp1RWgrYVlEdEVLczl2U2JCc1BlTGp0bFJIcTllQllTTzJvayttZGYKdlVvQXJCeE9WUU52
    RnVYczZxaG16aVZHeFN2TUR3bEM0NE5TWWFsdmJNV1RoTmMrRCtGMm9jM3hxU2tRZDZVTQpHSVhpZ2RD
    N2pLbTkwVEtBc29CVCtXM2IvMThFTmxhT09qSnBHWHM2RGJxU21WbFY3VzBkQ2tRUzlVUHIvM2taCkVF
    a0ZBZ1VpOVltWGdDRWZQR2J4ZnJTQzltNVNNVThmWlFkWWNpRVRnK2ZHMWtKM1NhU0xhQzhwcHVqODg1
    cUEKajV4UmVzQ0ZVbjdTdGlWckFDRGVVcCtKeWxvUHVMSkpDcE9Sa1o5b0FqWTZRSEtpaGpNSHVvcGtB
    K28wYmxVTQpHUUtDQVFFQXpPYTlPQ1dZeDJxUVFkRzdtWGNYblZKR3gyYVlpelZPS0tLM29xMDZWM0ls
    UlFhLzdCQnBoVjJxCnY4RTlZVEFZdWZhNlhDR1RVclpyeWRGdFk5ODl2Q0pPUmxCNmxKWEp2NjFuV1l1
    OWovQy9wVklJOEVQZ3J2VCsKWlZyMGdNY2x5eHZoRTZLRVZNM3AwSnIwNTZGMmdjWk1KOFBRWHQ5VkdF
    OXFYMmFaQVZ2M283MndCaWVSUWFMUgpuZ1o5ZWdPbG5mVC9xWTFzek1tc1RGaHhWNU5ydTZZaEtVb2Va
    QXJpbFpTWVNkNUNVZ2ZabnZwaWlwaHFaQlpzCloxT0tueHZXbFYrMVlxTVFNZWNGSWZGUDJhdXNjb0py
    Wks1VVkxK21HRFhwbytrWW9lTWtPc3Q5cEkxOVNHSFQKK2g3WldxS29Ra3BCMmZMeVNUUnNBTlV0WUxL
    TWdnPT0KLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=