apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: fag-order-gateway
    path: fag-deployments-order-gateway.yaml
  - target:
      kind: Ingress
      name: nginx-ingress
    path: fag-ingress-order-gateway.yaml
  - target:
      kind: ConfigMap
      name: fag-config
    path: fag-configmap-environment.yaml
  - target:
      kind: Secret
      name: tls-secret-nginx
    path: fag-secrets.yaml
  - target:
      kind: Role
      name: fag-role
    path: fag-role.yaml
  - target:
      kind: Ingress
      name: ingress-dashboards
    path: fag-ingress-dashboards.yaml
